/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paquete.clases;

/**
 *
 * @author matic
 */
public class VentanaGestionPartidos extends javax.swing.JFrame {

    private GestionPartidos gestor;
    

    /**
     * Creates new form VentanaGestionPartidos
     */
    public VentanaGestionPartidos(GestionPartidos gestor) {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.gestor = gestor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblSigla = new javax.swing.JLabel();
        txtSigla = new javax.swing.JTextField();
        lblRepresentante = new javax.swing.JLabel();
        txtRepresentante = new javax.swing.JTextField();
        chkLogo = new javax.swing.JCheckBox();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSalida = new javax.swing.JTextArea();
        txtIndice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Gestion de Partidos Politicos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 0, -1, -1));

        lblNombre.setText("Nombre del partido");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 43, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 40, 228, -1));

        lblSigla.setText("Sigla o simbolo");
        getContentPane().add(lblSigla, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 90, -1, -1));
        getContentPane().add(txtSigla, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 87, 50, -1));

        lblRepresentante.setText("Representante legal");
        getContentPane().add(lblRepresentante, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 130, -1, -1));
        getContentPane().add(txtRepresentante, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 127, 228, -1));

        chkLogo.setText("¿Tiene logo?");
        getContentPane().add(chkLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 161, -1, -1));

        btnAgregar.setText("Registrar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 227, -1, -1));

        btnModificar.setText("Modificar ");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 227, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 227, -1, -1));

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 227, -1, -1));

        jScrollPane2.setViewportView(jScrollPane3);

        txtSalida.setColumns(20);
        txtSalida.setRows(5);
        jScrollPane1.setViewportView(txtSalida);

        jScrollPane2.setViewportView(jScrollPane1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 288, 321, 116));

        txtIndice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIndiceActionPerformed(evt);
            }
        });
        getContentPane().add(txtIndice, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 193, 195, -1));

        jLabel2.setText("Indice para modificar o eliminar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 196, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombre.getText();
        char sigla = txtSigla.getText().charAt(0);
        boolean tieneLogo = chkLogo.isSelected();
        String representante = txtRepresentante.getText();

        gestor.registrarPartido(nombre, sigla, tieneLogo, representante);
        txtSalida.append("Partido registrado: " + nombre + "\n");
        
        txtSalida.append("Lista actual de partidos:\n");
        txtSalida.append(gestor.listarPartidos());
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        txtSalida.setText(gestor.listarPartidos());
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
            String textoIndice = txtIndice.getText().trim();

        if (!textoIndice.matches("\\d+")) {
            txtSalida.append("Ingresa un número válido en el campo índice.\n");
            return;
        }

        int indice = Integer.parseInt(textoIndice) - 1;

        if (indice >= 0 && indice < gestor.getCantidad()) {
            String nombre = txtNombre.getText().trim();
            String siglaStr = txtSigla.getText().trim();
            String representante = txtRepresentante.getText().trim();
            boolean tieneLogo = chkLogo.isSelected();

            if (nombre.isEmpty() || siglaStr.isEmpty() || representante.isEmpty()) {
                txtSalida.append("Completa todos los campos para modificar.\n");
                return;
            }

            char sigla = siglaStr.charAt(0);

            gestor.modificarPartido(indice, nombre, sigla, tieneLogo, representante);
            txtSalida.append("Partido modificado correctamente.\n");
        } else {
            txtSalida.append("Índice fuera de rango.\n");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        String textoIndice = txtIndice.getText().trim();

        if (!textoIndice.matches("\\d+")) {
            txtSalida.append("⚠️ Por favor, ingresa un número válido en el campo índice.\n");
            return;
        }

        int indice = Integer.parseInt(textoIndice) - 1;

        if (indice >= 0 && indice < gestor.getCantidad()) {
            gestor.eliminarPartido(indice);
            txtSalida.append("🗑️ Partido eliminado en la posición " + (indice + 1) + "\n");
        } else {
            txtSalida.append("⚠️ Índice fuera de rango.\n");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtIndiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIndiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIndiceActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JCheckBox chkLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRepresentante;
    private javax.swing.JLabel lblSigla;
    private javax.swing.JTextField txtIndice;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRepresentante;
    private javax.swing.JTextArea txtSalida;
    private javax.swing.JTextField txtSigla;
    // End of variables declaration//GEN-END:variables
}
