/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paquete.clases;

/**
 *
 * @author matic
 */
public class VentanaMenuPrincipal extends javax.swing.JFrame {

    // Declaración de atributos para los gestores
    private GestionCandidato gestorCandidatos = new GestionCandidato();
    private GestionPartidos gestorPartidos = new GestionPartidos();
    private GestionMesaElectoral gestorMesas = new GestionMesaElectoral();
    private GestionElecciones gestorElecciones = new GestionElecciones();
    private GestionActas gestorActas = new GestionActas();


    /**
     * Creates new form MenuPrincipal
     */
    public VentanaMenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);

        gestorCandidatos = new GestionCandidato();
        gestorPartidos = new GestionPartidos();
        gestorMesas = new GestionMesaElectoral();
        gestorElecciones = new GestionElecciones();
        gestorActas = new GestionActas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnActa = new javax.swing.JButton();
        btnCandidatos = new javax.swing.JButton();
        btnPartidos = new javax.swing.JButton();
        btnMesa = new javax.swing.JButton();
        btnEleccion = new javax.swing.JButton();
        bttnCerrar = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MENÚ PRINCIPAL DEL SISTEMA ELECTORAL");

        btnActa.setText("Registrar Acta Electoral");
        btnActa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActaActionPerformed(evt);
            }
        });

        btnCandidatos.setText("Gestionar Candidatos");
        btnCandidatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCandidatosActionPerformed(evt);
            }
        });

        btnPartidos.setText("Gestionar Partidos");
        btnPartidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartidosActionPerformed(evt);
            }
        });

        btnMesa.setText("Registrar Mesa Electoral");
        btnMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMesaActionPerformed(evt);
            }
        });

        btnEleccion.setText("Nueva Elección");
        btnEleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEleccionActionPerformed(evt);
            }
        });

        bttnCerrar.setText("Cerrar Sesión");
        bttnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCerrarActionPerformed(evt);
            }
        });

        btnReportes.setText("Ver Reportes");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnActa)
                            .addComponent(btnMesa))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCandidatos)
                            .addComponent(btnEleccion))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPartidos))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(btnReportes)
                                .addGap(0, 6, Short.MAX_VALUE)))))
                .addGap(110, 110, 110))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bttnCerrar)
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(134, 134, 134)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActa)
                    .addComponent(btnCandidatos)
                    .addComponent(btnPartidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEleccion)
                    .addComponent(btnMesa)
                    .addComponent(btnReportes))
                .addGap(83, 83, 83)
                .addComponent(bttnCerrar)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActaActionPerformed
        // TODO add your handling code here:
        VentanaRegistrarActa ventana = new VentanaRegistrarActa(gestorActas);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnActaActionPerformed

    private void bttnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCerrarActionPerformed
        // TODO add your handling code here:
        new Acceso_1().setVisible(true);
        dispose();
    }//GEN-LAST:event_bttnCerrarActionPerformed

    private void btnCandidatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCandidatosActionPerformed
        // TODO add your handling code here:
        VentanaGestionCandidatos ventana = new VentanaGestionCandidatos(gestorCandidatos);
        ventana.setVisible(true);

    }//GEN-LAST:event_btnCandidatosActionPerformed

    private void btnPartidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartidosActionPerformed
        // TODO add your handling code here:
        VentanaGestionPartidos ventana = new VentanaGestionPartidos(gestorPartidos);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnPartidosActionPerformed

    private void btnMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesaActionPerformed
        // TODO add your handling code here:
        VentanaGestionMesas ventana = new VentanaGestionMesas(gestorMesas);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnMesaActionPerformed

    private void btnEleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEleccionActionPerformed
        // TODO add your handling code here:
        VentanaNuevaEleccion ventana = new VentanaNuevaEleccion(gestorElecciones);
    ventana.setVisible(true);
    }//GEN-LAST:event_btnEleccionActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
        VentanaReporte ventana = new VentanaReporte(
        gestorCandidatos,
        gestorPartidos,
        gestorMesas,
        gestorElecciones,
        gestorActas
    );
    ventana.setVisible(true);
    }//GEN-LAST:event_btnReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActa;
    private javax.swing.JButton btnCandidatos;
    private javax.swing.JButton btnEleccion;
    private javax.swing.JButton btnMesa;
    private javax.swing.JButton btnPartidos;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton bttnCerrar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
